### ISSUE TITLE
Connect the database

### ISSUE THREAD

**Issue by SaharaSheik** [Face-Recognition-App-SD/Face-Recognition-Mobile#44]

**Comment by Guzt4vo** [comment]
Connection seems successful @benjnik6789 it may be worth looking into that warning that the db connection keeps giving: "MySQL Strict Mode is not set for database connection 'default' MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/3.2/ref/databases/#mysql-sql-mode" It may be an issue from end so I'll look into it as well
